name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "latest"

      - name: Update Core Index
        run: arduino-cli core update-index

      - name: Install Arduino AVR Core
        run: arduino-cli core install arduino:avr

      - name: Install Libraries
        run: |
          arduino-cli lib install U8g2
          arduino-cli lib install AccelStepper

      - name: Compile Firmware
        run: |
          mkdir -p build
          arduino-cli compile --fqbn arduino:avr:mega --output-dir ./build .

      # Upload compiled firmware as an artifact
      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: ./build/
